version: '3.7'
services:
  webserver:
    build: .
    user: root
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 23044
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin    
    ports:
      - "23044:23044"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./modules:/opt/airflow/modules/
      - ./airflow.cfg:/opt/airflow/airflow.cfg